// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMLgFEMOn5KSd-e6odO9Sa8-O7p2gX3Bc',
    appId: '1:380515099128:android:a951096dc040cf440a360d',
    messagingSenderId: '380515099128',
    projectId: 'w4-15-chatchanok',
    storageBucket: 'w4-15-chatchanok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBben8UxF4h9IUmSJ24QlwG8YaeIKaz6ek',
    appId: '1:380515099128:ios:9e3e0bbc43f73ed70a360d',
    messagingSenderId: '380515099128',
    projectId: 'w4-15-chatchanok',
    storageBucket: 'w4-15-chatchanok.firebasestorage.app',
    iosBundleId: 'com.example.w415Chatchanok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhYdPktPef-05J5HeEeJ7qkeNJQR6lRlk',
    appId: '1:380515099128:web:270b93665df2a81d0a360d',
    messagingSenderId: '380515099128',
    projectId: 'w4-15-chatchanok',
    authDomain: 'w4-15-chatchanok.firebaseapp.com',
    storageBucket: 'w4-15-chatchanok.firebasestorage.app',
  );
}
